version: "3.9"
services:
  webapp:
    build: ./
    ports:
      -   "8083:8083"
    depends_on:
      -   db
    environment:
      MOD_DB_PORT: "6379"
      MOD_DB_PASSWORD: ""
      MOD_DB_HOST: "mod-db"
      DB_KEYSPACE: "library"
      DB_IP: "db"
      DB_PORT: "9042"
  db:
    image: "cassandra:latest"
    ports:
      -   "9042:9042"
  mod-db:
    image: "redis:latest"
    ports:
      -   "6379:6379"