version: "3.9"
services:
  webapp:
    build: ./
    ports:
      -   "8083:8083"
    depends_on:
      -   db
    environment:
      DB_USERNAME: ""
      DB_PASSWORD: ""
      DB_URL: "jdbc:cassandra://db:9042/library;DefaultKeyspace=library"
      DB_KEYSPACE: "library"
      DB_IP: "db"
      DB_PORT: "9042"
  db:
    image: "cassandra:latest"
    ports:
      -   "9042:9042"